### ISSUE TITLE
DIN 5008 Print Format

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#19714]
**Is your feature request related to a problem? Please describe.**
Standard Print Formats in ERPNext are not suitable for German market as some requirements are not sufficient.
As a lot of invoices are still sent via paper in an envelope so we need the address to be visible in the envelopes windows. This is a country wide standard in A4 with certain boarder sizes etc.
I noticed that using "print" in ERPNext and using PDF->Print make two different things. These should be synchronized.

**Describe the solution you'd like**
I'm looking forward to a standard business letter format following DIN 5008 https://de.wikipedia.org/wiki/DIN_5008 .It would be great if I where to able to use the drag & drop feature you have implemented in Print Format, though we would not need the description. The customer name will do, a description like "customer" set in front of the customers name is not necessary.
In the German version you will also find the right mesurements
https://de.wikipedia.org/wiki/DIN_5008

**Describe alternatives you've considered**
We have had a custom made solution by @barredterra but he had trouble getting the right format into the system. It did some how work, but the regular print view was completely different to the one we see when generating the PDF.

**Additional context**
Furthermore especially on invoices it is recommended to have a subtotal at the end of the page which is carried forward to the next page.

The final touch: Also it is sufficient to have the company logo printed only on the first page. Many customers will even go so far to have pre-printed paper with their company logo and footer containing information like phone, address, website etc...

Here are some references:
https://rechnungen-muster.de/rechnungsvorlagen

**Comment by wojosc** [comment]
Please add Label "regional", "accounting", "DIN"

**Comment by barredterra** [comment]
This is the specification (Form B):

![](https://upload.wikimedia.org/wikipedia/commons/0/00/DIN_5008_Form_B.svg)

What we have so far:

**CSS**

Previously, all `mm` values from the specification had to be multiplied by `1.29` to match `wkhtmltopdf`'s resolution. This is not necessary anymore with frappe 12.0.20 and wkhtmltopdf 0.12.5 (with patched qt).
```css
#header {
    text-align: right;
    width: 100%;
    /* ( 45 mm - 10 mm margin ) */
    height: 35mm;
    /* Overwrite empty header inserted by frappe */
    margin-top: -10mm;
    overflow: hidden;
    padding-left: 32.25mm;
    padding-right: 25.8mm;
    position: relative;
}

#sender {
    position: relative;
    font-size: 75%;
    height: 17.7mm;
}

#sender p {
    position: absolute;
    bottom: 0;
}

#address {
    float: left;
    width: 85mm;
    padding-left: 5mm;
    margin-left: 20mm;
    height: 45mm;
    overflow: hidden;
}

#contact {
    width: 75mm;
    height: 40mm;
    overflow: hidden;
    margin-top: 5mm;
    margin-left: 20mm;
}

#contact>table {
    float: right;
    width: 100%;
}

#subject {
    margin-bottom: 2em;
    height: 5mm;
    font-weight: bold;
}

#faltmarke-1 {
    position: absolute;
    /* ( 105 mm - 10 mm margin ) */
    top: 95mm;
}

#lochmarke {
    position: absolute;
    /* ( 148.5 mm - 10 mm margin ) */
    top: 138.5mm;
}

#faltmarke-2 {
    position: absolute;
    /* ( 210 mm - 10 mm margin ) */
    top: 200mm;
}

#text {
    margin-top: 8.46mm;
    margin-left: 25mm;
    margin-right: 20mm;
}

#contact td {
    padding: 1.5px !important;
}

.text-right {
    text-align: right;
}

/* --- Nice page breaks for tables --- */
table {
    page-break-inside: auto
}

tr {
    page-break-inside: avoid;
    page-break-after: auto
}

thead {
    display: table-header-group
}

tfoot {
    display: table-footer-group
}
/* ---------------------------------- */

/* ------------- Footer ------------- */
#pagenum {
    text-align: right;
    margin-right: 20mm;
    margin-top: 4.23mm;
    margin-bottom: 4.23mm;
}

.footer-table>tbody>tr>td:not(:last-child) {
    padding: 0 30px 0 0 !important;
    
}

.footer-table>tbody>tr>td:last-child {
    padding: 0 !important;
}

.footer-table {
    font-size: 10pt;
    margin-left: 25mm;
    padding-right: 20mm;
}
/* ---------------------------------- */

```

**HTML Skeleton**
```html
<style>
    .print-format {
        margin-left: 0mm;
        margin-right: 0mm;
        margin-top: 10mm;
        margin-bottom: 55mm;
        font-size: 12pt;
    }
</style>

<div id="header">
    {{ letter_head }}
</div>

<div id="faltmarke-1">-</div>
<div id="lochmarke">-</div>
<div id="faltmarke-2">-</div>

<div id="address">
    <div id="sender">
        <!-- Company Address -->
    </div>
    <!-- Customer Address -->
</div>


<div id="contact">
    <table>
        <tr>
            <td>{{ _("Our Sign") }}:</td>
            <td class="text-right">{{ doc.name }}</td>
        </tr>
        <!-- Contact Information -->
        <!-- Date -->
</div>

<!-- CONTENT -->
<div id="text">
	<div id="subject">
        <!-- Subject / Heading -->
    </div>
        <!-- Greeting Text -->

        <!-- 


        Document Data 


        -->
</div>

<div id="footer-html" class="visible-pdf">
    <p id="pagenum">
        {{ _("Page {0} of {1}").format('<span class="page"></span>', '<span class="topage"></span>') }}
    </p>
    {{ footer }}
</div>
```
