### ISSUE TITLE
Unable to upgrade to ERPNEXT v13.15.1 and FRAPPE v13.15.0 - /assets/* permission errors

### ISSUE THREAD

**Issue by rodenp** [frappe/erpnext#28625]
## Description of the issue
Upgrading to ERPNEXT v13.15.1 and FRAPPE v13.15.0 produces permission errors

## Context information (for bug reports)
Updated docker .env file

changed ERPNEXT_VERSION=v13.14.0 to v13.15.1
changed FRAPPE_VERSION=v13.14.0 to v13.15.0

**Output of `bench version`**
erpnext 13.15.1
frappe 13.15.0

## Steps to reproduce the issue

1. docker-compose --project-name vc down
2. update ERPNEXT_VERSION to v13.15.1 and FRAPPE_VERSION to v13.15.0
3. docker-compose pull
3. docker-compose --project-name vc up -d
4. inspect logs

### Observed result (extract - log is huge)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/.package.json.aa7mgT" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/.github/.FUNDING.yml.PaiK2S" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/benchmark/.index.js.rMp4iU" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/benchmark/.test.json.jCBtQQ" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/example/.key_cmp.js.gA3x4R" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/example/.nested.js.0WGwIQ" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/example/.str.js.I3AY2Q" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/example/.value_cmp.js.thlkKU" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/test/.cmp.js.Z3db3T" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/test/.nested.js.62REzT" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/test/.str.js.5hGROU" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fast-json-stable-stringify/test/.to-json.js.Zd3axQ" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.LICENSE.6IY8LT" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.README.md.lQ6VhU" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.bench.js.Nkx2CT" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.example.js.OPUX9T" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.index.d.ts.CdecuR" failed: Permission denied (13)
rsync: [receiver] mkstemp "/assets/frappe/node_modules/fastq/.package.json.ck5RkT" failed: Permission denied (13)
## Additional information

OS version / distribution, `ERPNext` install method, etc.
Linux localhost 5.4.0-81-generic #91-Ubuntu, docker-compose

**Comment by dabruh** [comment]
I've got the same issue. I've tried upgrading from `v13.13.0/v13.13.0` (Frappe/ERPNext) to `v13.15.0/v13.15.2` without luck. I've managed to upgrade to `v13.14.0/v13.14.0`, but I can't go to `v13.15.0/v13.15.2` from there. I did try to set the owner of my Docker volumes to my current user, instead of root, but that didn't help much - however, it seemed to get rid of the permission errors in the logs, but then I was just stuck with the blank 404 page when trying to access ERPNext. I didn't dig much deeper than that. I'm on 5.14.18-1-MANJARO using Docker Compose.

**Comment by rodenp** [comment]
Like @dabruh, I am able to upgrade to v13.14.0/v13.14.0 but anything after that I get permission errors.

________________________________

**Comment by itg-dave** [comment]
Got it to work:

1. Add another service to docker-compose.yml and let nginx depend on it. Change nginx traefik label to port 8080 if you didn't pull the latest docker-compose or customized it like me...
   ```yml
   # [...]
   erpnext-nginx:
     # [...]
     labels:
      # [...]
       - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080"
     depends_on:
       - fix-vol-permissions
   # [...]
   fix-vol-permissions:
     image: frappe/frappe-worker:${ERPNEXT_VERSION}
     user: root
     command: chown -R 1000:1000 /sites /assets /logs
     volumes:
       - sites-vol:/sites
       - assets-vol:/assets
       - logs-vol:/logs
   # [...]
   ```
2. `docker-compose --project-name <your-project-name> up -d --force-recreate`

https://github.com/frappe/frappe_docker/issues/567

**Comment by ankush** [comment]
Seems to be frappe_docker related. Closing this issue, continue discussion in frappe_docker issue if required.

**Comment by dabruh** [comment]
@Dave3o3 Yep, now it's working after I did as you described.

I did `git pull` on the main branch and I currently have [this docker-compose.yaml](https://github.com/frappe/frappe_docker/blob/91648299bace49d9190c6e914c4738092e990c88/docker-compose.yml).

I added the service and dependency after line 50 in the file:

```yaml
...
      - "${CERT_RESOLVER_LABEL}"
      - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
    depends_on:
      - fix-vol-permissions

  fix-vol-permissions:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    user: root
    command: chown -R 1000:1000 /sites /assets /logs
    volumes:
      - sites-vol:/sites
      - assets-vol:/assets
      - logs-vol:/logs

  erpnext-python:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
...
```

However, the image you have set (`frappe/frappe-worker:${ERPNEXT_VERSION}`) is not valid with the ERPNEXT_VERSION set to `v13.15.2`. I changed the image to `frappe/erpnext-worker`.

An interesting detail is that I've managed to start it now after removing the new service - so the one-time task seems to have been sufficient. However, what I find weird is that I did set the permissions of these volumes manually before I found this issue, but it didn't help much other than resolving the permission issue  - ERPNext still wouldn't start, for other reasons.

How did this even happen? @revant seems to have been playing with the [fix-vol-permissions service in the docker-compose.yaml](https://github.com/frappe/frappe_docker/commit/91648299bace49d9190c6e914c4738092e990c88). We'll have to open an issue over at [frappe_docker](https://github.com/frappe/frappe_docker), but I gotta do some accounting first. :-)

**Comment by rodenp** [comment]
Like @dabruh I replaced my docker-compose with the latest version and added the fix-vol-permissions changes.
Now i can update to the latest versions of ERPNEXT and FRAPPE without any extra changes. 
There is a risk that new docker users will also encounter issues and not know what to do.
This would not be a good experience for new users and would not give them much confidence in the system.
This has also exposed a vulnerability in your testing that should prevent issues like this making it into production.
So please could someone raise the issue at frappe_docker, so that this does not get lost.

**Comment by revant** [comment]
Latest frappe-nginx and erpnext-nginx images are now non-root unprivileged. That does not allow the container to start port < 1000 and files to be accessed need to be owned by uid:gid 1000:1000.

That means,

1) the loadbalancer port in traefik or k8s ingress need to be changed from 80 to 8080

and 

2) the files to be accessed `logs`, `assets` and `sites` need to be owned by 1000:1000


related: https://discuss.erpnext.com/t/frappe-docker-ode-modules-core-js-internals-is-forced-js-sndqlp/82870/2

**Comment by dabruh** [comment]
@revant I did change the permissions to 1000:1000, but I got other errors then. This is the relevant section of my currently operational docker-compose.yaml concerning the ports:

```yaml
...
services:
  traefik:
    image: "traefik:v2.2"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      # enable traefik
      - "traefik.enable=true"
      # global redirect to https for production only
      - "${HTTPS_REDIRECT_RULE_LABEL}"
      - "${HTTPS_REDIRECT_ENTRYPOINT_LABEL}"
      - "${HTTPS_REDIRECT_MIDDLEWARE_LABEL}"
      # middleware redirect for production only
      - "${HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-vol:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: "host"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - SKIP_NGINX_TEMPLATE_GENERATION=${SKIP_NGINX_TEMPLATE_GENERATION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"
      - "${ENTRYPOINT_LABEL}"
      - "${CERT_RESOLVER_LABEL}"
      - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
...
```
